# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HviDYIynGhMufFcWtQKLKsnbNzd-_z_R
"""

import numpy as np
np.set_printoptions(precision=2, suppress=True)
A = np.array([[1,2,0], [0,0,5], [3,-4,2], [1,6,5],[0,1,0]])
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
frob = np.linalg.norm(A)
evklid = np.linalg.norm(A, 2)
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')
print(f'Евклидова норма:{evklid}')
print(f'Норма Фробениуса:{frob}')